# -*- coding: utf-8 -*-
"""Day-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H9PNPXtqSyF-F4YEr10Oc3SLDucA578J
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

import seaborn as sns

df = sns.load_dataset('tips')
df.head()

df.shape

df.dtypes

"""Numerical variables"""

df.corr()

sns.heatmap(df.corr())

sns.jointplot(x='tip', y='total_bill', data=df, kind='reg')

sns.pairplot(df)

sns.pairplot(df, hue='day')

sns.countplot('smoker', data=df)

sns.countplot(y='smoker', data=df)

#barplot
sns.barplot(y = 'total_bill', x= 'sex', data = df)

sns.barplot( x= 'smoker', y = 'tip', data = df)

#Boxplot

sns.boxplot(y = 'total_bill', x= 'sex', data = df)

sns.boxplot( x='total_bill', y = 'day', hue = 'smoker', data = df, orient="h")

#Violin plot

sns.violinplot(x='total_bill', y = 'day', hue = 'smoker', data = df)